SELECT COUNT(*) FROM SAAS.SAAS_DATA.RAW_ACCOUNTS;
SELECT COUNT(*) FROM SAAS.SAAS_DATA.RAW_USERS;
SELECT COUNT(*) FROM SAAS.SAAS_DATA.RAW_PLANS;
SELECT COUNT(*) FROM SAAS.SAAS_DATA.RAW_SUBSCRIPTIONS;
SELECT COUNT(*) FROM SAAS.SAAS_DATA.RAW_PAYMENTS;
SELECT COUNT(*) FROM SAAS.SAAS_DATA.RAW_EVENTS;

DESC TABLE SAAS.SAAS_DATA.RAW_ACCOUNTS;
DESC TABLE SAAS.SAAS_DATA.RAW_USERS;
DESC TABLE SAAS.SAAS_DATA.RAW_PLANS;
DESC TABLE SAAS.SAAS_DATA.RAW_SUBSCRIPTIONS;
DESC TABLE SAAS.SAAS_DATA.RAW_PAYMENTS;
DESC TABLE SAAS.SAAS_DATA.RAW_EVENTS;


-- SUBSCRIPTION EDA
SELECT * FROM SAAS.SAAS_DATA.RAW_SUBSCRIPTIONS 
WHERE subscription_status='active';

SHOW TABLES IN SCHEMA SAAS.SAAS_DATA;
DESC TABLE SAAS.SAAS_DATA.RAW_SUBSCRIPTIONS;

SELECT * FROM SAAS.SAAS_DATA.RAW_SUBSCRIPTIONS LIMIT 10; 

SELECT* FROM SAAS.SAAS_DATA.RAW_SUBSCRIPTIONS
WHERE subscription_end_date IS NULL 
AND subscription_status = 'canceled';

SELECT account_id , plan_id, subscription_status FROM SAAS.SAAS_DATA.RAW_SUBSCRIPTIONS
GROUP BY plan_id, subscription_status,account_id
HAVING subscription_status = 'active';


SELECT* FROM SAAS.SAAS_DATA.RAW_SUBSCRIPTIONS
WHERE subscription_end_date IS NOT NULL 
AND subscription_status = 'active';

SELECT subscription_start_date, subscription_end_date, plan_id FROM SAAS.SAAS_DATA.RAW_SUBSCRIPTIONS
GROUP BY subscription_start_date, subscription_end_date, plan_id 


SELECT account_id, subscription_start_date, subscription_end_date, created_at FROM SAAS.SAAS_DATA.RAW_SUBSCRIPTIONS
GROUP BY account_id, subscription_start_date, subscription_end_date, created_at
ORDER BY account_id ASC;

SELECT account_id, subscription_start_date, subscription_end_date, created_at FROM SAAS.SAAS_DATA.RAW_SUBSCRIPTIONS
GROUP BY account_id, subscription_start_date, subscription_end_date, created_at

HAVING subscription_end_date IS NOT NULL
ORDER BY account_id ASC;

-- PAYMENTS EDA 
SELECT * FROM SAAS.SAAS_DATA.RAW_PAYMENTS

SELECT* from SAAS.SAAS_DATA.RAW_PAYMENTS
WHERE payment_status IN ('failed');

SELECT* from SAAS.SAAS_DATA.RAW_PAYMENTS
WHERE amount < 0;

SELECT* from SAAS.SAAS_DATA.RAW_PAYMENTS
WHERE payment_date IN ('2026-02-09');

SELECT* from SAAS.SAAS_DATA.RAW_PAYMENTS
WHERE created_at IN ('2026-02-09');

SELECT* from SAAS.SAAS_DATA.RAW_PAYMENTS
WHERE created_at IN ('2025-09-09');

-- ACCOUNT WITH HIGH REFUND
SELECT ACCOUNT_ID, amount from SAAS.SAAS_DATA.RAW_PAYMENTS
WHERE amount < 0
GROUP BY ACCOUNT_ID, AMOUNT
ORDER BY amount ASC;

-- ACCOUNT WITH HIGH REFUND
SELECT SUBSCRIPTION_ID, amount from SAAS.SAAS_DATA.RAW_PAYMENTS
WHERE amount < 0
GROUP BY SUBSCRIPTION_ID, AMOUNT
ORDER BY amount ASC;

-- ACCOUNT WITH HIGHEST REFUNDS
SELECT
*
FROM SAAS.SAAS_DATA.RAW_PAYMENTS
WHERE subscription_id ='S16' AND amount < 0;

-- ACCOUNT WITH MOST REFUNDS
SELECT amount, subscription_id,
COUNT(subscription_id) AS sub FROM SAAS.SAAS_DATA.RAW_PAYMENTS
WHERE amount < 0
GROUP BY subscription_id, amount
ORDER BY sub DESC;

--EVENTS EDA
SELECT * FROM SAAS.SAAS_DATA.RAW_EVENTS
ORDER BY user_id ASC, account_id ASC, created_at ASC;

SELECT COUNT(*) FROM SAAS.SAAS_DATA.RAW_EVENTS;

SELECT COUNT(*) FROM SAAS.SAAS_DATA.RAW_EVENTS
WHERE EVENT_TYPE IN ('featue_call');

SELECT COUNT(*) FROM SAAS.SAAS_DATA.RAW_EVENTS
WHERE EVENT_TYPE IN ('api_call');

SELECT COUNT(*) FROM SAAS.SAAS_DATA.RAW_EVENTS
WHERE EVENT_TYPE IN ('export');

SELECT COUNT(*) FROM SAAS.SAAS_DATA.RAW_EVENTS
WHERE EVENT_TYPE IN ('export');

-- how much percent would be ?
SELECT
    COUNT(CASE WHEN EVENT_TYPE = 'export' THEN 1 END) * 100.0
    / COUNT(*) AS export_percentage
FROM SAAS.SAAS_DATA.RAW_EVENTS;

SELECT * FROM SAAS.SAAS_DATA.RAW_EVENTS
ORDER BY account_id ASC, USER_ID ASC, EVENT_TIMESTAMP ASC;

SELECT account_id, user_id, event_timestamp FROM SAAS.SAAS_DATA.RAW_EVENTS
ORDER BY account_id ASC, USER_ID ASC, EVENT_TIMESTAMP ASC

-- top 10 account used most usage
SELECT account_id, COUNT(account_id) AS rank
FROM SAAS.SAAS_DATA.RAW_EVENTS
GROUP BY account_id
ORDER BY rank DESC
LIMIT 10;

-- top 10 user with most usage
SELECT user_id,
COUNT(user_id) AS u_rank
FROM SAAS.SAAS_DATA.RAW_EVENTS
GROUP BY user_id
ORDER BY u_rank DESC
LIMIT 10;

